version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/krayber

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file

hooks:

  BeforeInstall:

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root
