version: '3.1'

services:
#  api:
#    env_file:
#      development.env
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 3000:3000
#    depends_on:
#      - elasticsearch
#    links:
#      - elasticsearch:elasticsearch
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    networks:
#      - docker_elk

  elasticsearch:
    image: elasticsearch:6.5.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - docker_elk


  kibana:
    image: kibana:6.5.0
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
       - docker_elk
networks:
  docker_elk:
    driver: bridge


#  postgres:
#    image: postgres:alpine
#    env_file:
#      development.env
#    ports:
#      - "5432:5432"
#    restart: always
#
#  pgAdmin:
#    image: dpage/pgadmin4
#    env_file:
#      development.env
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    restart: always
#    links:
#      - postgres:postgres
