version: '3.1'

services:
  api:
    env_file:
      development.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

#  postgres:
#    image: postgres:alpine
#    env_file:
#      development.env
#    ports:
#      - "5432:5432"
#    restart: always
#
#  pgAdmin:
#    image: dpage/pgadmin4
#    env_file:
#      development.env
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    restart: always
#    links:
#      - postgres:postgres
